Translated record form
mysociety/alaveteli pull request #6111
Opened 2021-02-11 15:41 UTC by garethrees

## Relevant issue(s)

In service of #5911.

## What does this do?

Add `TranslatedRecordForm` form builder

## Why was this needed?

Make it easier to add translated record admin interfaces.

## Implementation notes

## Screenshots

## Notes to reviewer

2021-02-11 17:03 UTC, garethrees commented
Transient spec error – `bin/rspec spec/helpers/` sometimes passes locally.

2021-02-12 15:03 UTC, gbp commented
> Transient spec error – `bin/rspec spec/helpers/` sometimes passes locally.

Example failing spec command:
`rspec './spec/helpers/admin/translated_record_form_spec.rb[1:1:2:1]' './spec/helpers/public_body_helper_spec.rb[1:2:5:1]' --seed 33252`

2021-02-12 16:27 UTC, gbp commented
Transient spec error is due to rows not being cleared from the database between runs. This case is fixed in #6112

2021-02-12 16:40 UTC, gbp requested changes
This is almost there... comments inline

2021-02-12 16:40 UTC, gbp commented on spec/helpers/admin/translated_record_helper_spec.rb
> +    it { is_expected.to eq(expected) }
This spec isn't proving anything without the new form builder methods being used. We don't want to expect those methods are outputting the HTML here so I would consider using a `to receive` or `to have_received` matcher to check the `builder` argument is used.

2021-02-18 11:18 UTC, merged