Hide wizard content from non js users
mysociety/alaveteli pull request #6306
Opened 2021-06-10 12:56 UTC by wrightmartin

## Relevant issue(s)

#5938 

## What does this do?

Hides the wizard and wizard content from clients without javascript

## Why was this needed?

The wizard is (currently) JS dependant so won't work with JS disabled or where the JS files haven't loaded

## Implementation notes

## Screenshots

## Notes to reviewer

2021-06-10 13:17 UTC, garethrees commented
@wrightmartin got any screenshots for the PR so that I know what I'm expecting to see?

2021-06-10 14:31 UTC, garethrees requested changes
I've had a quick look at this. I don't know if I'm missing something vs what you intended, but I'm not sure this does anything differently to the behaviour prior to the change?

I can see two issues at the moment that this change doesn't cover.

1. We say "Hey, use our refusals wizard" below, which won't be there.
2. We say "Get help with refusals" and render nothing. That doesn't feel great.

![Screenshot 2021-06-10 at 15 27 36](https://user-images.githubusercontent.com/282788/121543071-8aa7de00-ca00-11eb-9595-bca879dd4d81.png)

2021-06-10 15:54 UTC, wrightmartin commented
ah sorry for the confusion, there's a WDTK PR that comes along with it that hides that content, I've just found the PR sat in an open tab not submitted

2021-06-24 11:17 UTC, gbp approved these changes

2021-06-24 11:25 UTC, merged