[#6294] Add Debian Bullseye support
mysociety/alaveteli pull request #6615
Opened 2021-10-29 09:40 UTC by gbp

## Relevant issue(s)

Requires https://github.com/mysociety/sysadmin/issues/1530
Requires https://github.com/mysociety/commonlib/pull/77
~Requires https://github.com/mysociety/alaveteli/issues/6489 or https://github.com/mysociety/alaveteli/issues/6656~
Requires #6053 
Fixes #6294 

## What does this do?

Adds Debian Bullseye support

## Why was this needed?

Framework modernisation

## Notes to reviewer

~~I have build a Vagrant box with the above PRs merged and `wkhtmltox` replaced with `wkhtmltopdf` and all specs pass.~~

2021-11-03 11:09 UTC, gbp commented
<details>
<summary>Output from vagrant box build</summary>
<pre>
[nix-shell:~/alaveteli]$ bin/vagrant-bullseye up 
Bringing machine 'bullseye' up with 'virtualbox' provider...
==> bullseye: Importing base box 'debian/bullseye64'...
==> bullseye: Matching MAC address for NAT networking...
==> bullseye: Checking if box 'debian/bullseye64' version '11.20211018.1' is up to date...
==> bullseye: Setting the name of the VM: alaveteli_bullseye_1635936447262_57973
==> bullseye: Clearing any previously set network interfaces...
==> bullseye: Preparing network interfaces based on configuration...
    bullseye: Adapter 1: nat
    bullseye: Adapter 2: hostonly
==> bullseye: Forwarding ports...
    bullseye: 22 (guest) => 2222 (host) (adapter 1)
==> bullseye: Running 'pre-boot' VM customizations...
==> bullseye: Booting VM...
==> bullseye: Waiting for machine to boot. This may take a few minutes...
    bullseye: SSH address: 127.0.0.1:2222
    bullseye: SSH username: vagrant
    bullseye: SSH auth method: private key
    bullseye: 
    bullseye: Vagrant insecure key detected. Vagrant will automatically replace
    bullseye: this with a newly generated keypair for better security.
    bullseye: 
    bullseye: Inserting generated public key within guest...
    bullseye: Removing insecure key from the guest if it's present...
    bullseye: Key inserted! Disconnecting and reconnecting using new SSH key...
==> bullseye: Machine booted and ready!
==> bullseye: Checking for guest additions in VM...
    bullseye: The guest additions on this VM do not match the installed version of
    bullseye: VirtualBox! In most cases this is fine, but in rare cases it can
    bullseye: prevent things such as shared folders from working properly. If you see
    bullseye: shared folder errors, please make sure the guest additions within the
    bullseye: virtual machine match the version of VirtualBox you have installed on
    bullseye: your host and reload your VM.
    bullseye: 
    bullseye: Guest Additions Version: 6.0.0 r127566
    bullseye: VirtualBox Version: 6.1
==> bullseye: Setting hostname...
==> bullseye: Configuring and enabling network interfaces...
==> bullseye: Mounting shared folders...
    bullseye: /home/vagrant/alaveteli => /home/gbp/alaveteli
    bullseye: /home/vagrant/alaveteli-themes => /home/gbp/alaveteli-themes
==> bullseye: Running provisioner: shell...
    bullseye: Running: inline script
    bullseye: DEVELOPMENT INSTALL
    bullseye: ==== Installing alaveteli
    bullseye: Updating package lists... 
    bullseye: done
    bullseye: Installing some core packages...
    bullseye:   apt-utils... 
    bullseye: done
    bullseye:   git... 
    bullseye: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    bullseye: done
    bullseye:   locales... 
    bullseye: done
    bullseye:   lockfile-progs... 
    bullseye: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    bullseye: done
    bullseye:   curl... 
    bullseye: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    bullseye: done
    bullseye:   dnsutils... 
    bullseye: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    bullseye: done
    bullseye:   lsb-release... 
    bullseye: done
    bullseye:   gnupg... 
    bullseye: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    bullseye: done
    bullseye: Testing for being on EC2... 
    bullseye: done
    bullseye: WARNING: tempfile is deprecated; consider using mktemp instead.
    bullseye: Generating locales... 
    bullseye: E: Unable to locate package language-pack-en
    bullseye: Generating locale en_GB... 
    bullseye: adding and generating... 
    bullseye: Generating locales (this might take a while)...
    bullseye:   en_GB.UTF-8
    bullseye: ...
    bullseye:  done
    bullseye: Generation complete.
    bullseye: done
    bullseye: done
    bullseye: Adding unix user... 
    bullseye: already done
    bullseye: Updating APT sources... 
    bullseye: W: Target Sources (main/source/Sources) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list.d/mysociety-extra.list:7
    bullseye: W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Translations (main/i18n/Translation-en_GB) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Sources (main/source/Sources) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list.d/mysociety-extra.list:7
    bullseye: W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Translations (main/i18n/Translation-en_GB) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: done
    bullseye: Cloning or updating repository... 
    bullseye: skipping as development install... done
    bullseye: Updating mySociety APT source... 
    bullseye: Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
    bullseye: OK
    bullseye: W: Target Sources (main/source/Sources) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list.d/mysociety-extra.list:7
    bullseye: W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Translations (main/i18n/Translation-en_GB) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Sources (main/source/Sources) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list.d/mysociety-extra.list:7
    bullseye: W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Translations (main/i18n/Translation-en_GB) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/mysociety-extra.list:6
    bullseye: done
    bullseye: W: Target Sources (main/source/Sources) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list.d/mysociety-extra.list:7
    bullseye: W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt [...]

2021-11-09 16:50 UTC, garethrees reviewed
Currently getting this failure:

```
    default: Adding unix user... already done
    default: Updating APT sources... Unsupported distribution and version combination debian n/a
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

We're checking for this when [updating apt sources](https://github.com/mysociety/commonlib/blob/565037b/bin/install-site.sh#L132-L161).

Commonlib looks up to date:

```
gareth: ~/tmp/alaveteli/commonlib ((565037b...))
$ git ls -3
565037b Merge branch 'install-gnupg' (Graeme Porteous <graeme@rgbp.co.uk>)
673e260 Add GNU Privacy Guard to core packages (Graeme Porteous <graeme@rgbp.co.uk>)
fb0804f Merge branch 'change-debian-mirror' (Graeme Porteous <graeme@rgbp.co.uk>)
```

Manually running [the commands](https://github.com/mysociety/commonlib/blob/565037b/bin/install-site.sh#L659-L660) that generate the variables we check, it appears that for some reason we're getting `n/a` returned as the OS Codename:

```
vagrant@alaveteli-bullseye64:~$ lsb_release -i -s  | tr A-Z a-z
debian
vagrant@alaveteli-bullseye64:~$ lsb_release -c -s
n/a
vagrant@alaveteli-bullseye64:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        11-updates
Codename:       n/a
```

2021-11-09 16:57 UTC, garethrees commented
FWIW

```
$ vagrant box list | grep bullseye
debian/bullseye64        (virtualbox, 11.20210409.1)
```

2021-11-09 17:06 UTC, gbp commented
> ```
> $ vagrant box list | grep bullseye
> debian/bullseye64        (virtualbox, 11.20210409.1)
> ```

In the output above my machine used `11.20211018.1`. So looks like the vagrant box has been updated. Maybe run `vagrant box update` ?

2021-11-09 17:08 UTC, garethrees commented
> In the output above my machine used `11.20211018.1`. So looks like the vagrant box has been updated. Maybe run `vagrant box update` ?

Yeah noticed that after commenting and running again after update, which seems to be getting further 👌

2021-11-10 09:31 UTC, garethrees requested changes
As per https://github.com/mysociety/sysadmin/issues/1530#issuecomment-964940090, it looks like this PR requires https://github.com/mysociety/alaveteli/issues/6489.

Can we make [France's patch](https://gitlab.com/madada-team/dada-core/-/merge_requests/49/diffs#fa435e52585380593620a0b0294adb50b63741a9_701_712) in core? Might have to add a conditional that checks `wkhtmltopdf --version` so that we retain compatibility, but that's a boatload easier than replacing it right now.

2021-11-10 09:33 UTC, gbp commented
> Can we make [France's patch](https://gitlab.com/madada-team/dada-core/-/merge_requests/49/diffs#fa435e52585380593620a0b0294adb50b63741a9_701_712) in core? Might have to add a conditional that checks `wkhtmltopdf --version` so that we retain compatibility, but that's a boatload easier than replacing it right now.

Yeah can do that. I'm abit wary about using the `enable-local-file-access` option although I guess that is no difference that what v0.11 is currently doing.

2021-11-11 12:30 UTC, garethrees approved these changes
Decided against requiring #6489 so good to go – just add a changelog entry 👍

2021-11-11 16:15 UTC, merged