[#1005] Hide individual attachments
mysociety/alaveteli pull request #7327
Opened 2022-09-27 10:48 UTC by gbp

## Relevant issue(s)

Fixes #1005

## What does this do?

1. Adds attachment admin UI
2. Adds prominence and reason to `FoiAttachment`
3. Show prominence notice in frontend
4. Add checks for attachments with prominence before downloading/viewed as HTML
5. Prevents attachments with prominence from being indexed by Xapian

## Why was this needed?

Easier admin of responses and attachments.

## Screenshots

### Incoming message admin
![image](https://user-images.githubusercontent.com/5426/192503016-1d544408-a0f3-4d3f-8fd8-d3d2c3e8aced.png)

### Attachment admin
![image](https://user-images.githubusercontent.com/5426/192503817-1e322410-34ce-49d6-92a3-a885b8986ec4.png)

### Hidden attachment as public / Hidden attachment as requester
![image](https://user-images.githubusercontent.com/5426/192505376-e3bb7fee-7a42-40b3-9796-fe6c3eca9f52.png)

### Hidden attachment as site admin
![image](https://user-images.githubusercontent.com/5426/192505329-da8243a0-aa9f-481c-ae74-13948c8aceae.png)

### Requester only attachment as public
![image](https://user-images.githubusercontent.com/5426/192504166-9c7217be-9a48-4c7c-8eb0-42579e417da1.png)

### Requester only attachment as requester
![image](https://user-images.githubusercontent.com/5426/192504931-616e46a9-930c-4798-9d90-1705961031fc.png)

### Requester only attachment as site admin
![image](https://user-images.githubusercontent.com/5426/192504988-3c4a5bb8-689c-438c-95a1-246eee7162af.png)

### Hidden main body attachment as public / Hidden main body attachment as requester
![image](https://user-images.githubusercontent.com/5426/192505751-1a4c9429-fcb3-4c90-975e-58aaf2f9b447.png)

### Hidden main body attachment as site admin
![image](https://user-images.githubusercontent.com/5426/192505678-1fbe6297-623e-4f3a-8c22-f50ab2bac08c.png)

### Requester only main body attachment as public
![image](https://user-images.githubusercontent.com/5426/192506250-df851cb2-3b1f-485a-993e-e9807dade689.png)

### Requester only main body attachment as requester
![image](https://user-images.githubusercontent.com/5426/192506121-2557a28a-0317-4c1f-9649-47e1f73d1dd1.png)

### Requester only main body attachment as site admin
![image](https://user-images.githubusercontent.com/5426/192506040-3f68137c-bf97-4108-bd7c-f21078d0fb9a.png)

2022-09-29 08:34 UTC, gbp commented on app/helpers/admin/link_helper.rb
> +    link_to(icon, foi_attachment_path(foi_attachment), title: title) + ' ' +
This does link directly to the attachment which is why we have change we're discussing here: https://github.com/mysociety/alaveteli/pull/7324#discussion_r981102135

2022-09-29 08:36 UTC, garethrees commented on app/helpers/admin/link_helper.rb
> +    link_to(icon, foi_attachment_path(foi_attachment), title: title) + ' ' +
Ah, sorry for not being clear.

I appreciate it links to e.g. `/request/foo_bar_baz_2#attachment-77`. What I meant by "directly link to" was `/request/125/response/23/attach/2/fs%2050379341.pdf`

2022-09-29 08:41 UTC, gbp commented on app/controllers/admin/foi_attachments_controller.rb
> +      render action: 'edit'
We don't do this in the other admin controllers.

2022-09-29 08:44 UTC, garethrees commented on app/controllers/admin/foi_attachments_controller.rb
> +      render action: 'edit'
I don't think we do when we show model validation errors, but doesn't look like we're doing that here so a fail would be completely silent. I think we only need a `error: 'Save unsuccessful'` flash on the end of the `render` call.

2022-09-29 08:45 UTC, gbp commented on app/controllers/admin/foi_attachments_controller.rb
> +      redirect_to edit_admin_incoming_message_path(@incoming_message)
Re-rendering the form isn't normally done on successful submission, normally we would redirect to the `#show` or `#index` actions but we don't have those, the `incoming_message#edit` action is the closest thing we have. Saying that happy to change if you want.

2022-09-29 08:47 UTC, garethrees commented on app/controllers/admin/foi_attachments_controller.rb
> +      redirect_to edit_admin_incoming_message_path(@incoming_message)
Yeah, I guess on save I was feeling like I wanted to go back in to `#edit` to check that the record was now as I expected. There's no reason for it not to be – just psychological! Let's leave it as it is for now as it's an easy change if we want to tweak it later.

2022-09-29 08:49 UTC, gbp commented on app/controllers/attachments_controller.rb
> +      )
I think I missed the fact `render_hidden` renders a template and not a partial. In which case I don't think this is needed. I will revert this commit

2022-09-29 08:50 UTC, gbp commented on app/models/incoming_message.rb
> +  def get_attachments_for_search_index
I certainly agree with this but not in this PR. This method follows the style of other methods in this class which need extracting and renaming.

2022-09-29 08:52 UTC, gbp commented on spec/controllers/attachments_controller_spec.rb
> +    it 'should not generate an HTML version of an attachment for a request whose prominence is hidden even for an admin but should return a 404' do
Copy-pasted the spec description which is now wrong, the attachment has `hidden` prominence.

2022-09-29 08:52 UTC, gbp commented on spec/controllers/attachments_controller_spec.rb
> +    it 'should not generate an HTML version of an attachment for a request whose prominence is hidden even for an admin but should return a 404' do
Copy-pasted the spec description which is now wrong, the attachment has `hidden` prominence.

2022-09-29 08:54 UTC, gbp commented on app/views/request/hidden_attachment.html.erb
> +<%- if !attachment.prominence_reason.blank? %>
I think I missed edited this file. It should replicate the `request/hidden_correspondence.html.erb` template.

2022-09-29 08:54 UTC, garethrees commented on spec/controllers/attachments_controller_spec.rb
> +    it 'should not generate an HTML version of an attachment for a request whose prominence is hidden even for an admin but should return a 404' do
Yeah, I guessed that might be the only issue. My other thought was whether it ought to be testing e.g. hitting a "normal" prominence attachment but the InfoRequest is "hidden". Might be covered elsewhere

2022-10-18 12:33 UTC, gbp commented
@garethrees this should be working now. There is loads of fixups do you want to see those or should I go ahead and rebase before you re-review?

2022-10-18 12:45 UTC, gbp commented
Specs are green locally not sure why GitHub actions aren't running.

2022-10-18 14:06 UTC, garethrees commented
> There is loads of fixups do you want to see those or should I go ahead and rebase before you re-review?

Happy to review as-is.

> Specs are green locally not sure why GitHub actions aren't running.

Might be because of the merge conflict?

2022-10-21 14:49 UTC, garethrees commented
On running I get:

<img width="501" alt="Screenshot 2022-10-21 at 15 43 45" src="https://user-images.githubusercontent.com/282788/197224461-5dfea85e-9a23-4e25-ad61-0a53456dd6b6.png">

Fixed with:

```diff
diff --git a/app/helpers/prominence_helper.rb b/app/helpers/prominence_helper.rb
index 2a26944b4..c81994e99 100644
--- a/app/helpers/prominence_helper.rb
+++ b/app/helpers/prominence_helper.rb
@@ -98,7 +98,7 @@ def default_prominence_reason
     end
   end

-  class InfoRequest::Prominence::Helper < Base # :nodoc:
+  class InfoRequest::Prominence::Helper < ProminenceHelper::Base # :nodoc:
     def user
       prominenceable.user
     end
@@ -166,6 +166,8 @@ def sign_in_notice(*args)

   ::OutgoingMessage::Prominence::Helper = IncomingMessage::Prominence::Helper

+  module FoiAttachment::Prominence ; end
+
   class FoiAttachment::Prominence::Helper < Base # :nodoc:
     def user
       prominenceable.incoming_message.info_request.user
```

2022-10-21 15:08 UTC, gbp commented
> On running I get:
> 

Missed a file, pushed a fixup

2022-10-21 15:39 UTC, garethrees requested changes
As an admin user I though I should be able to see reduced-prominence main body parts below the prominence reason?

<img width="756" alt="Screenshot 2022-10-21 at 16 25 47" src="https://user-images.githubusercontent.com/282788/197232501-9f440940-ab17-471c-af0f-9d4890bf570d.png">

I think this is getting quite a big and complicated PR, so maybe let's pair on this on Monday to get some of the more incidental parts merged, and then get left with just the main body of work that adds attachment prominence.

2022-10-21 15:39 UTC, garethrees commented on app/models/ability.rb
> +      can_view_with_prominence?(attachment.prominence, attachment.incoming_message.info_request)
This doesn't cover the case where the `FoiAttachment` is "normal", but it's `IncomingMessage` is reduced prominence. In this situation you can still view the attachment if you know its direct URL (which search engines will). I think it needs to be like:

```ruby
can_view_with_prominence?(attachment.prominence, attachment.incoming_message.info_request) &&
  can?(:read, attachment.incoming_message)
```

This is pretty critical behaviour, so I think it needs tests, somewhere….

2022-10-21 15:39 UTC, garethrees commented on app/models/incoming_message.rb
> -  def get_attachments_for_search_index
Not clear why this is getting removed here?

2022-10-24 16:05 UTC, gbp commented
Superseded by #7391

2022-10-24 16:05 UTC, closed without merging