Quote request title in notification emails
mysociety/alaveteli pull request #7352
Opened 2022-10-07 08:48 UTC by garethrees

We had some user feedback [1] that interpolating the request title into some phrases could be quite confusing because it wasn't obvious where the request title started and ended, and how it fits in to what we're trying to communicate.

[1] https://twitter.com/MrDanack/status/1578072110739722243

Might be worth writing a script to update the translation strings here, as this creates some extra work for translators which isn't totally necessary.

2022-10-07 08:58 UTC, gbp commented
> Might be worth writing a script to update the translation strings here, as this creates some extra work for translators which isn't totally necessary.

Will need something for the prominence strings too so happy to do this when we do the next release.

2022-10-07 09:28 UTC, garethrees commented
> Will need something for the prominence strings too so happy to do this when we do the next release.

Great! I've added this one to https://github.com/mysociety/alaveteli/issues/6603#issuecomment-1271348508 – feel free to just edit my comment to include the PR(/s) you were thinking of.

2022-10-14 13:14 UTC, garethrees commented
Be nice to have https://github.com/mysociety/alaveteli/tree/add-mailer-previews for reviewing.

2022-10-20 08:49 UTC, gbp requested changes

2022-10-21 11:59 UTC, garethrees commented on spec/views/request_mailer/new_response_reminder_alert.text.erb_spec.rb
> +    expect(response).to match("Your request was called 'Apostrophe's'")
Sorry, I should have explicitly noted that single quotes are what we use in many of the unchanged email templates, so this change was just applying the existing pattern everywhere.

We could change that pattern I suppose, but in most cases request titles won't have quotes/apostrophes or other punctuation that would add confusion.

2022-10-21 16:34 UTC, garethrees commented on spec/views/request_mailer/new_response_reminder_alert.text.erb_spec.rb
> +    expect(response).to match("Your request was called 'Apostrophe's'")
We could use curly quotes, but there's still the possibility that users include them in their request titles too (though slightly less likely than an apostrophe).

2022-12-22 13:37 UTC, merged